import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppProviders } from "@/components/providers";
import AdminSheet from "@/components/AdminSheet";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  console.log("🚀 ~ file: layout.tsx:22 ~ router:", router);
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProviders attribute="class" defaultTheme="system" enableSystem>
          <AdminSheet />
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
